name: gif_search_app
description: "A gif search application using the Giphy service."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-110.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.0
  go_router: ^13.0.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.2
  json_annotation: ^4.9.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
